* ox-blog
The =ox-blog= package allows you to write and publish a blog from within emacs.
- livereload (reload browser on export)
- categories
- drafts
- small enough to read through it
  - < 1000 lines of code (~ 500 at the time of writing)
  - just =htmlize=, =org-mode 9+= & =emacs 25+=

The goal is to provide a user-friendly blogging environment for emacs that just works™.
** TODO API (TODO)
*** Functions
- =org-blog-export= export with drafts
- =org-blog-publish= export production (hide drafts) & push =export-directory= repository to origin
*** Variables
- =org-blog-project= project plist, similar to a single entry from =org-publish-project-alist=
- =org-blog-draft-prefix=
- =org-blog--template-index=
- =org-blog--template-index-item=
- =org-blog--template-category-js=
- =org-blog--server-livereload-script=
*** Custom project options
- =:source-directory=
- =:export-directory=
- =:port=
- =:babel-evaluate=
- =:babel-header-args=
- =:index-head=
** Setup
To get started you need set =org-blog-project= and provide a source and an
export directory. Then just start writing and call =org-blog-export= to
export.
#+BEGIN_SRC elisp
(setq org-blog-project '(:source-directory "~/blog/source"
                         :export-directory "~/blog/export"))
#+END_SRC

See the =source/= folder for an example configuration.
* Develoment
#+BEGIN_SRC sh
make install
make test
#+END_SRC
